### ISSUE TITLE
H3 modbusLAN

### ISSUE THREAD

**Issue by domerich** [rsaemann/HA-FoxESS-H3-Modbus#1]
Hello guys I have the H3 8kW hybrid inverter with ew11 RS485 to WLAN interface.

I tried to implement but I get nothing.

in the configuration.yaml I have

```
modbus: !include modbusLAN.yaml

#Sensors turn power values into power/hour values for meters
sensor: 
  - method: left
    name: pv1_sum
    platform: integration
    round: 2
    source: sensor.pv1_power
    unit_time: h
  - method: left
    name: pv2_sum
    platform: integration
    round: 2
    source: sensor.pv2_power
    unit_time: h

 #Templates enable math operations against states/values to give us better data
template:
  - sensor:
      - name: "Battery Discharge"  #absolute value. 0 when charging
        device_class: "power"
        unit_of_measurement: "W"
        state: >
            {% if (states('sensor.battery_discharge_power') | float(default=0) ) > 0 %}
            {{ states('sensor.battery_discharge_power') | float(default=0) * 1 }}
            {% else %}
            0 
            {% endif %}
      - name: "Battery Charge"   #absolute value. 0 when discharging
        device_class: "power"
        unit_of_measurement: "W"
        state: >
            {% if (states('sensor.battery_discharge_power') | float(default=0) ) < 0 %}
            {{ states('sensor.battery_discharge_power') | float(default=0) * -1 }}
            {% else %}
            0 
            {% endif %}
      - name: "Inverter Load power"
        device_class: "power"
        unit_of_measurement: "W"
        state: >
               {{ (states('sensor.load_power_r') | float(default=0)
               + states('sensor.load_power_s') | float(default=0)
               + states('sensor.load_power_t') | float(default=0)) | round(2) }}
      - name: "Meter Power"
        device_class: "power"
        unit_of_measurement: "W" #negative=consumption/importing from grid
        state: >
            {{ states('sensor.meter_power_r') | float(default=0)
            + states('sensor.meter_power_s') | float(default=0)
            + states('sensor.meter_power_t') | float(default=0)
            }}
      - name: "Inverter Feed In Power"  #positive or zero
        device_class: "power"
        unit_of_measurement: "W"
        state: >
            {% if (states('sensor.inverter_load_power') | float(default=0) ) > 0 %}
            {{ states('sensor.inverter_load_power') | float(default=0) }}
            {% else %}
            0 
            {% endif %}
      - name: "Inverter Grid Consumption"  #positive or zero
        device_class: "power"
        unit_of_measurement: "W"
        state: >
            {% if (states('sensor.inverter_load_power') | float(default=0) ) < 0 %}
            {{ states('sensor.inverter_load_power') | float(default=0) * -1 }}
            {% else %}
            0 
            {% endif %}
      - name: "PV Power Now"
        device_class: "power"
        unit_of_measurement: "W"
        state: >
              {{ (states('sensor.pv1_power') | float(default=0) + states('sensor.pv2_power') | float(default=0) ) }}
      - name: "Inverter System Losses"
        device_class: "power"
        unit_of_measurement: "W"
        state: >
               {{ ((states('sensor.pv1_power') | float(default=0)
               + states('sensor.pv2_power') | float(default=0)
               + states('sensor.inverter_grid_consumption') | float(default=0) 
               + states('sensor.battery_discharge_power') | float(default=0) 
               - states('sensor.inverter_load_power') | float(default=0) )) | round(2) }}
      - name: "EPS remaining time"
        device_class: "duration"
        unit_of_measurement: "hours"
        # hardcoded values here: 20% minimum SoC (not usable), 14kWh battery total capacity -> 140 kwh/% strange unit
        state: >
               {{ (((states('sensor.battery_soc') | float(default=0)) -20)*140
               / (states('sensor.inverter_load_power') | float(default=0))) | round(2) }}
# Utility Meters - Provides meters to be used with the energy dashboard and reset daily
utility_meter:
  pv1_daily:
    source: sensor.pv1_sum
    cycle: daily
  pv2_daily:
    source: sensor.pv2_sum
    cycle: daily
  losses_daily:
    source: sensor.losses_sum
    cycle: daily
```

and in modbusLAN.yaml I have

```
# v0.1
# Modbus Config for Fox ESS Hybrid H3 Inverter
# Adapted by https://github.com/rsaemann/HA-FoxESS-H3-Modbus
# Original for H1 inverters Created by https://github.com/StealthChesnut/HA-FoxESS-Modbus

# ---------------------------RS485 Connection----------------------------------------
#  For use when connecting to RS485 port of inverter
#
- name: HA-FoxESS-Modbus-LAN
  type: tcp
  host: 192.168.178.189 # set to USR devices ip address
  port: 502
# 
# ---------------------------------------------------------------------------
# Device ID ("Slave", standard: 247) can be set in inverter menu configuration->communication->RS485->DeviceID
  sensors:
    - name: "PV1-Voltage"
      unique_id: foxess_inv1_pv1_voltage
      scan_interval: 30
      slave: 247
      address: 31000
      state_class: measurement
      unit_of_measurement: "V"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: holding
      device_class: voltage
    - name: "PV1-Current"
      unique_id: foxess_inv1_pv1_current
      scan_interval: 30
      slave: 247
      address: 31001
      state_class: measurement
      unit_of_measurement: "A"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: holding      
      device_class: current
    - name: "PV1-Power"
      unique_id: foxess_inv1_pv1_power
      scan_interval: 30
      slave: 247
      address: 31002
      state_class: measurement
      unit_of_measurement: "W"
      data_type: int16
      scale: 1
      precision: 0
      input_type: holding      
      device_class: power
    - name: "PV2-Voltage"
      unique_id: foxess_inv1_pv2_voltage
      scan_interval: 30
      slave: 247
      address: 31003
      state_class: measurement
      unit_of_measurement: "V"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: holding
      device_class: voltage
    - name: "PV2-Current"
      unique_id: foxess_inv1_pv2_current
      scan_interval: 30
      slave: 247
      address: 31004
      state_class: measurement
      unit_of_measurement: "A"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: holding      
      device_class: current
    - name: "PV2-Power"
      unique_id: foxess_inv1_pv2_power
      scan_interval: 30
      slave: 247
      address: 31005
      state_class: measurement
      unit_of_measurement: "W"
      data_type: int16
      scale: 1
      precision: 0
      input_type: holding  
      device_class: power
#section main grid output
    - name: "Grid Voltage R" # Grid Voltage formerly named: "Volt L1"
      unique_id: foxess_inv1_grid_voltage_R
      scan_interval: 30
      slave: 247
      address: 31006
      state_class: measurement
      unit_of_measurement: "V"
      data_type: int16
      precision: 2
      scale: 0.1
      input_type: holding
      device_class: voltage
    - name: "Grid Voltage S" # Grid Voltage formerly named: "Volt L2"
      unique_id: foxess_inv1_grid_voltage_S
      scan_interval: 30
      slave: 247
      address: 31007
      state_class: measurement
      unit_of_measurement: "V"
      data_type: int16
      precision: 2
      scale: 0.1
      input_type: holding
      device_class: voltage
    - name: "Grid Voltage T" # Grid Voltage formerly named: "Volt L3"
      unique_id: foxess_inv1_grid_voltage_T
      scan_interval: 30
      slave: 247
      address: 31008
      state_class: measurement
      unit_of_measurement: "V"
      data_type: int16
      precision: 2
      scale: 0.1
      input_type: holding
      device_class: voltage
    - name: "Inv Current R" #Main out current L1
      unique_id: foxess_inv1_inv_current_R
      scan_interval: 30
      address: 31009
      state_class: measurement
      unit_of_measurement: "A"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: holding      
      device_class: current
    - name: "Inv Current S" #Main out current L2
      unique_id: foxess_inv1_inv_current_S
      scan_interval: 30
      address: 31010
      state_class: measurement
      unit_of_measurement: "A"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: holding      
      device_class: current
    - name: "Inv Current T" #Main out current L3
      unique_id: foxess_inv1_inv_current_T
      scan_interval: 30
      address: 31011
      state_class: measurement
      unit_of_measurement: "A"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: holding      
      device_class: current
    - name: "Inv Power R"
      unique_id: foxess_inv1_inv_power_R
      scan_interval: 30
      slave: 247
      address: 31012
      state_class: measurement
      unit_of_measurement: "W"
      data_type: int16
      scale: 1
      precision: 0
      input_type: holding  
      device_class: power
    - name: "Inv Power S"
      unique_id: foxess_inv1_inv_power_S
      scan_interval: 30
      slave: 247
      address: 31013
      state_class: measurement
      unit_of_measurement: "W"
      data_type: int16
      scale: 1
      precision: 0
      input_type: holding  
      device_class: power
    - name: "Inv Power T"
      unique_id: foxess_inv1_inv_power_T
      scan_interval: 30
      slave: 247
      address: 31014
      state_class: measurement
      unit_of_measurement: "W"
      data_type: int16
      scale: 1
      precision: 0
      input_type: holding  
      device_class: power
    - name: "Grid Frequency" # Grid Frequency
      unique_id: foxess_inv1_grid_frequency
      scan_interval: 30
      slave: 247
      address: 31015
      state_class: measurement
      unit_of_measurement: "Hz"
      data_type: int16
      scale: 0.01
      precision: 2
      input_type: holding
      device_class: frequency

#section EPS output
    - name: "EPS Power R" # eps power formerly named:"L1 Power"
      unique_id: foxess_inv1_eps_power_R
      scan_interval: 30
      slave: 247
      address: 31022
      state_class: measurement
      unit_of_measurement: "W"
      data_type: int16
      scale: 1
      precision: 0
      input_type: holding  
      device_class: power
    - name: "EPS Power S" # eps power formerly named:"L2 Power"
      unique_id: foxess_inv1_eps_power_S
      scan_interval: 30
      slave: 247
      address: 31023
      state_class: measurement
      unit_of_measurement: "W"
      data_type: int16
      scale: 1
      precision: 0
      input_type: holding  
      device_class: power
    - name: "EPS Power T" # eps power formerly named:"L3 Power"
      unique_id: foxess_inv1_eps_power_T
      scan_interval: 30
      slave: 247
      address: 31024
      state_class: measurement
      unit_of_measurement: "W"
      data_type: int16
      scale: 1
      precision: 0
      input_type: holding  
      device_class: power
      
    - name: "EPS Frequency" # Grid Frequency formerly named: "Freq"
      unique_id: foxess_inv1_eps_frequency
      scan_interval: 30
      slave: 247
      address: 31025
      state_class: measurement
      unit_of_measurement: "Hz"
      data_type: int16
      scale: 0.01
      precision: 2
      input_type: holding
      device_class: frequency
#section Smartmeter current values
# only active, if smart meter is connected
    - name: "Meter Power R" 
      unique_id: foxess_meter1_power_r
      scan_interval: 30
      slave: 247
      address: 31026
      state_class: measurement
      unit_of_measurement: "W"      #negative value= consumption/import
      data_type: int16
      scale: 1
      precision: 0
      input_type: holding  
      device_class: power
    - name: "Meter Power S" 
      unique_id: foxess_meter1_power_s
      scan_interval: 30
      slave: 247
      address: 31027
      state_class: measurement
      unit_of_measurement: "W"      #negative value= consumption/import
      data_type: int16
      scale: 1
      precision: 0
      input_type: holding  
      device_class: power
    - name: "Meter Power T" 
      unique_id: foxess_meter1_power_t
      scan_interval: 30
      slave: 247
      address: 31028
      state_class: measurement
      unit_of_measurement: "W"      #negative value= consumption/import
      data_type: int16
      scale: 1
      precision: 0
      input_type: holding  
      device_class: power
   
# Load = Main+EPS
    - name: "Load Power R" 
      unique_id: foxess_inv1_load_power_r
      scan_interval: 30
      slave: 247
      address: 31029
      state_class: measurement
      unit_of_measurement: "W"
      data_type: int16
      scale: 1
      precision: 0
      input_type: holding  
      device_class: power
    - name: "Load Power S" 
      unique_id: foxess_inv1_load_power_s
      scan_interval: 30
      slave: 247
      address: 31030
      state_class: measurement
      unit_of_measurement: "W"
      data_type: int16
      scale: 1
      precision: 0
      input_type: holding  
      device_class: power
    - name: "Load Power T" 
      unique_id: foxess_inv1_load_power_t
      scan_interval: 30
      slave: 247
      address: 31031
      state_class: measurement
      unit_of_measurement: "W"
      data_type: int16
      scale: 1
      precision: 0
      input_type: holding  
      device_class: power
    #Temperatures
    - name: "Inv Temperature"
      unique_id: foxess_inv1_inverter_temperature
      scan_interval: 30
      slave: 247
      address: 31032
      state_class: measurement
      unit_of_measurement: "°C"
      data_type: int16
      scale: 0.1
      precision: 1
      device_class: temperature
      input_type: holding    
    - name: "Inner Temperature"
      unique_id: foxess_inv1_internal_temperature
      scan_interval: 30
      slave: 247
      address: 31033
      state_class: measurement
      unit_of_measurement: "°C"
      data_type: int16
      scale: 0.1
      precision: 1
      device_class: temperature
      input_type: holding
    
    #Battery
    - name: "Battery Voltage"
      unique_id: foxess_inv1_battery_voltage
      scan_interval: 30
      address: 31034
      state_class: measurement
      unit_of_measurement: "V"
      data_type: int16
      scale: 0.1
      precision: 1
      device_class: voltage
      input_type: holding
    - name: "Battery Current"
      unique_id: foxess_inv1_battery_current
      scan_interval: 30
      address: 31035
      state_class: measurement
      unit_of_measurement: "A"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: holding      
      device_class: current
    - name: "Battery Discharge Power" #negative values=charging battery
      unique_id: foxess_inv1_battery_power
      scan_interval: 30
      slave: 247
      address: 31036
      state_class: measurement
      unit_of_measurement: "W"
      data_type: int16
      scale: 1
      precision: 0
      input_type: holding    
      device_class: power
    - name: "Battery Temperature"
      unique_id: foxess_inv1_battery_temperature
      scan_interval: 60
      slave: 247
      address: 31037
      state_class: measurement
      unit_of_measurement: "°C"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: temperature
    - name: "Battery SoC"
      unique_id: foxess_inv1_battery_soc
      scan_interval: 30
      slave: 247
      address: 31038
      state_class: measurement
      unit_of_measurement: "%"
      data_type: int16
      input_type: holding
      device_class: battery

#cumulative values of Energy
    - name: "PV Energy total"
      unique_id: foxess_inv1_total_pv_energy
      scan_interval: 60
      slave: 247
      address: 32001
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
    - name: "PV Energy daily"
      unique_id: foxess_inv1_daily_pv_energy
      scan_interval: 60
      slave: 247
      address: 32002
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
      
    - name: "Battery Charge Energy total"
      unique_id: foxess_inv1_total_charge_energy
      scan_interval: 60
      slave: 247
      address: 32004
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
    - name: "Battery Charge Energy daily"
      unique_id: foxess_inv1_daily_charge_energy
      scan_interval: 60
      slave: 247
      address: 32005
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
      
    - name: "Battery Discharge Energy total"
      unique_id: foxess_inv1_total_discharge_energy
      scan_interval: 60
      slave: 247
      address: 32007
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
    - name: "Battery Discharge Energy daily"
      unique_id: foxess_inv1_daily_discharge_energy
      scan_interval: 60
      slave: 247
      address: 32008
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
      # registers working with a connected smart meter only:
      # 32009-32020
      # 
    - name: "Meter Feed-in Energy total"
      unique_id: foxess_sm1_total_feedin_energy
      scan_interval: 60
      slave: 247
      address: 32010
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
    - name: "Meter Feed-in Energy daily"
      unique_id: foxess_sm1_daily_feedin_energy
      scan_interval: 60
      slave: 247
      address: 32011
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
    - name: "Meter Consumption Energy total"
      unique_id: foxess_sm1_total_consumption_energy
      scan_interval: 60
      slave: 247
      address: 32013
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
    - name: "Meter Consumption Energy daily"
      unique_id: foxess_sm1_daily_consumption_energy
      scan_interval: 60
      slave: 247
      address: 32014
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
    - name: "Meter Output Energy total"
      unique_id: foxess_sm1_total_output_energy
      scan_interval: 60
      slave: 247
      address: 32016
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
    - name: "Meter Output Energy daily"
      unique_id: foxess_sm1_daily_output_energy
      scan_interval: 60
      slave: 247
      address: 32017
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
    - name: "Meter Input Energy total"
      unique_id: foxess_sm1_total_input_energy
      scan_interval: 60
      slave: 247
      address: 32019
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
    - name: "Meter Input Energy daily"
      unique_id: foxess_sm1_daily_input_energy
      scan_interval: 60
      slave: 247
      address: 32020
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
    #Grid+EPS values? officially: "Load" energy
    - name: "Inv Load Energy total" #formerly named: "EPS Energy total"
      unique_id: foxess_inv1_total_load_energy
      scan_interval: 60
      slave: 247
      address: 32022
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
    - name: "Inv Load Energy daily"  #formerly named: "EPS Energy daily"
      unique_id: foxess_inv1_daily_load_energy
      scan_interval: 60
      slave: 247
      address: 32023
      state_class: total_increasing
      unit_of_measurement: "kWh"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: holding
      device_class: energy
```

Can anybody please help?
